[project]
name = "auth"
description = "Authentication components for login/registration"
readme = "README.md"

dependencies = [
    "htmpl:components/core>=0.0.1",
    "htmpl:services/oauth",
    "python:ptjwt>=2.8.0",
]
